Updated Program to output results for BP Tables
NeighborhoodInfoDC/BridgePk pull request #3
Opened 2017-06-01 23:17 UTC by jdev42092

Added code to:
1) Output ACS 2011-2015 population counts/ denominators for population
shares
2) Output # of rental units from ACS
3) Separated number of single family and condo units from RealProp
4) Added code to output 1990, 2000, and 2010 Census figures on total
population and household count from NCDB

2017-06-01 23:19 UTC, jdev42092 commented
@NeighborhoodInfoDC/review This program (which outputs results for our Bridge Park Data Tables) is ready for review.

2017-06-02 13:05 UTC, ptatian commented
Will review

2017-06-02 18:37 UTC, ptatian requested changes
Looks good, Jay. Just a few small changes. Thanks.

2017-06-02 18:37 UTC, ptatian commented on Prog/BPKPresentationResults.sas
> +libname Bridgepk "L:\Libraries\Bridgepk\Data\";
You shouldn't need to use a libname statement here. You should use %DCData_lib() as with the other libraries.

2017-06-02 18:37 UTC, ptatian commented on Prog/BPKPresentationResults.sas
> +property_crime_rate_2014 property_crime_rate_2015);
Should be able to add 2016 crime data.

2017-06-02 20:07 UTC, jdev42092 commented
@ptatian Thanks for those suggestions, Peter. I incorporated both of them. Is this ok to merge and batch submit?

2017-06-02 20:24 UTC, ptatian commented
Yes, please go ahead and merge. Thanks.

2017-06-02 21:28 UTC, merged